// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {storage} from '../models';
import {execution} from '../models';
import {runner} from '../models';

export function AvailableToolchains():Promise<Array<project.ToolchainInfo>>;

export function CancelRun(arg1:string):Promise<void>;

export function ChooseProjectDirectory():Promise<string>;

export function DeleteProjectEnvVar(arg1:string,arg2:string):Promise<void>;

export function DeleteProjectSnippet(arg1:string,arg2:string):Promise<void>;

export function DiscoverRunTargets(arg1:string):Promise<Array<project.RunTarget>>;

export function FormatSnippet(arg1:string):Promise<string>;

export function Health():Promise<storage.HealthReport>;

export function OpenProject(arg1:string):Promise<project.OpenProjectResult>;

export function ProjectEnvVars(arg1:string):Promise<Array<storage.EnvVarRecord>>;

export function ProjectSnippets(arg1:string):Promise<Array<storage.SnippetRecord>>;

export function RecentProjects(arg1:number):Promise<Array<storage.ProjectRecord>>;

export function RunSnippet(arg1:execution.RunRequest):Promise<execution.Result>;

export function SaveProjectSnippet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<storage.SnippetRecord>;

export function SetProjectDefaultPackage(arg1:string,arg2:string):Promise<storage.ProjectRecord>;

export function SetProjectToolchain(arg1:string,arg2:string):Promise<storage.ProjectRecord>;

export function SetProjectWorkingDirectory(arg1:string,arg2:string):Promise<storage.ProjectRecord>;

export function StartProjectWorker(arg1:string):Promise<runner.Worker>;

export function StartupError():Promise<string>;

export function StopProjectWorker(arg1:string):Promise<void>;

export function UpsertProjectEnvVar(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<storage.EnvVarRecord>;
