// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AvailableToolchains() {
  return window['go']['desktop']['WailsBridge']['AvailableToolchains']();
}

export function CancelRun(arg1) {
  return window['go']['desktop']['WailsBridge']['CancelRun'](arg1);
}

export function ChooseProjectDirectory() {
  return window['go']['desktop']['WailsBridge']['ChooseProjectDirectory']();
}

export function DeleteProjectEnvVar(arg1, arg2) {
  return window['go']['desktop']['WailsBridge']['DeleteProjectEnvVar'](arg1, arg2);
}

export function DeleteProjectSnippet(arg1, arg2) {
  return window['go']['desktop']['WailsBridge']['DeleteProjectSnippet'](arg1, arg2);
}

export function DiscoverRunTargets(arg1) {
  return window['go']['desktop']['WailsBridge']['DiscoverRunTargets'](arg1);
}

export function FormatSnippet(arg1) {
  return window['go']['desktop']['WailsBridge']['FormatSnippet'](arg1);
}

export function Health() {
  return window['go']['desktop']['WailsBridge']['Health']();
}

export function OpenProject(arg1) {
  return window['go']['desktop']['WailsBridge']['OpenProject'](arg1);
}

export function ProjectEnvVars(arg1) {
  return window['go']['desktop']['WailsBridge']['ProjectEnvVars'](arg1);
}

export function ProjectSnippets(arg1) {
  return window['go']['desktop']['WailsBridge']['ProjectSnippets'](arg1);
}

export function RecentProjects(arg1) {
  return window['go']['desktop']['WailsBridge']['RecentProjects'](arg1);
}

export function RunSnippet(arg1) {
  return window['go']['desktop']['WailsBridge']['RunSnippet'](arg1);
}

export function SaveProjectSnippet(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['WailsBridge']['SaveProjectSnippet'](arg1, arg2, arg3, arg4);
}

export function SetProjectDefaultPackage(arg1, arg2) {
  return window['go']['desktop']['WailsBridge']['SetProjectDefaultPackage'](arg1, arg2);
}

export function SetProjectToolchain(arg1, arg2) {
  return window['go']['desktop']['WailsBridge']['SetProjectToolchain'](arg1, arg2);
}

export function SetProjectWorkingDirectory(arg1, arg2) {
  return window['go']['desktop']['WailsBridge']['SetProjectWorkingDirectory'](arg1, arg2);
}

export function StartProjectWorker(arg1) {
  return window['go']['desktop']['WailsBridge']['StartProjectWorker'](arg1);
}

export function StartupError() {
  return window['go']['desktop']['WailsBridge']['StartupError']();
}

export function StopProjectWorker(arg1) {
  return window['go']['desktop']['WailsBridge']['StopProjectWorker'](arg1);
}

export function UpsertProjectEnvVar(arg1, arg2, arg3, arg4) {
  return window['go']['desktop']['WailsBridge']['UpsertProjectEnvVar'](arg1, arg2, arg3, arg4);
}
